export const LOADERS = {
  LOGIN_LOADING: "LOGIN_LOADING",
};

export const USER_TYPES = {
  LOAD_LOGIN: "LOAD_LOGIN",
  LOGGED_USER: "LOGGED_USER",
};

export const NOTIFIER = {
  ERROR_MESSAGE: "ERROR_MESSAGE",
  SUCCESS_MESSAGE: "SUCCESS_MESSAGE",
};

export const COOKIE_NAME = {
  AUTH_TOKEN: "AUTH_TOKEN",
};

export const PRODUCT_TYPES = {
  ADDED_NEW_PRODUCT_MODEL: "ADDED_NEW_PRODUCT_MODEL",
  ADDED_NEW_PRODUCT_DETAIL: "ADDED_NEW_PRODUCT_DETAIL",
  ADDED_NEW_PRODUCT_IMG_AND_DESC: "ADDED_NEW_PRODUCT_IMG_AND_DESC",
  FINISH_NEW_PRODUCT_ADD: "FINISH_NEW_PRODUCT_ADD",
};
