export const USER_AUTH_TYPES = {
  LOGIN: {
    LOAD_LOGIN: "LOAD_LOGIN",
    LOAD_LOGIN_SUCCESS: "LOAD_LOGIN_SUCCESS",
    LOAD_LOGIN_FAILURE: "LOAD_LOGIN_FAILURE",
    LOAD_LOGGED_SUCCESS: "LOAD_LOGGED_SUCCESS",
  },
  SIGNUP: {
    LOAD_SIGNUP: "LOAD_SIGNUP",
    LOAD_SIGNUP_SUCCESS: "LOAD_SIGNUP_SUCCESS",
    LOAD_SIGNUP_FAILURE: "LOAD_SIGNUP_FAILURE",
  },
  AUTH: {
    LOAD_ACCREDIT: "LOAD_ACCREDIT",
    ACCREDITED: "ACCREDITED",
  },
};
