export const GLOBAL_ERROR = "GLOBAL_ERROR";
export const GLOBAL_SUCCESS = "GLOBAL_SUCCESS";
export const GLOBAL_SUCCESS_WITH_IMG = "GLOBAL_SUCCESS_WITH_IMG";

export const WEBSITE_LOAD = "WEBSITE_LOAD";

export const IS_LOADING = "IS_LOADING";

export const USER_AUTH_TYPES = {
  LOGIN: {
    LOAD_LOGIN: "LOAD_LOGIN",
    LOAD_LOGGGED_USER: "LOAD_LOGGED_USER",
  },
  SIGNUP: {
    LOAD_SIGNUP: "LOAD_SIGNUP",
    LOAD_SIGNED_UP_USER: "LOAD_SIGNED_UP_USER",
  },
  MESSAGE: {
    LOAD_AUTH_SUCCESS_MESSAGE: "LOAD_AUTH_SUCCESS_MESSAGE",
    LOAD_AUTH_FAILURE_MESSAGE: "LOAD_AUTH_FAILURE_MESSAGE",
  },
  USER_STATUS: {
    LOAD_ACCREDITATION: "LOAD_ACCREDITATION",
    IS_LOGGED_IN: "IS_LOGGED_IN",
    LOAD_USER: "LOAD_USER",
    GET_USER: "GET_USER",
  },

  USER_LOGOUT: {
    LOAD_LOGOUT: "LOAD_LOGOUT",
  },

  USER_PASSWORD: {
    LOAD_FORGOT_PASSWORD: "LOAD_FORGOT_PASSWORD",
    LOAD_RESET_PASSWORD: "LOAD_RESET_PASSWORD",
  },

  USER_UPDATE: {
    USER_PASSWORD_CHANGE: "USER_PASSWORD_CHANGE",
  },
};

export const COOKIE_NAMES = {
  AUTH_TOKEN: "AUTH_TOKEN",
  CART_ITEMS: "CART_ITEMS",
};

export const RE_OCCURING_REQUESTS = {
  RE_OCCURING_PRODUCT_DETAIL: "RE_OCCURING_PRODUCT_DETAIL",
};

export const PRODUCT_TYPES = {
  GET_ALL_CATEGORIES: "GET_ALL_CATEGORIES",

  LOAD_GET_PRODUCTS_BASED_ON_QUERY: "LOAD_GET_PRODUCTS_BASED_ON_QUERY",
  GET_PRODUCTS_BASED_ON_QUERY: "GET_PRODUCTS_BASED_ON_QUERY",
  HOLD_PREVIOUS_REQUESTED_QUERY: "HOLD_PREVIOUS_REQUESTED_QUERY",
  SET_NUMBER_OF_RESULTS_PERPAGE: "SET_NUMBER_OF_RESULTS_PERPAGE",
  SET_PAGE_NUMBER: "SET_PAGE_NUMBER",
  NO_MORE_RESULTS_FOUND: "NO_MORE_RESULTS_FOUND",

  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  LOAD_PRODUCT_CART: "LOAD_PRODUCT_CART",
  GET_PRODUCTS_IN_CART: "GET_PRODUCTS_IN_CART",

  LOAD_VIEW_PRODUCT_DETAIL: "LOAD_VIEW_PRODUCT_DETAIL",
  PRODUCT_DETAIL: "PRODUCT_DETAIL",

  LOAD_PRODUCT_REVIEWS: "LOAD_PRODUCT_REVIEWS",
  GET_PRODUCT_REVIEWS: "GET_PRODUCT_REVIEWS",
  REVIEW_FOUND_HELPFUL: "REVIEW_FOUND_HELPFUL",

  LOAD_NEW_PRODUCT_REVIEW: "LOAD_NEW_PRODUCT_REVIEW",
};

export const LOADERS = {
  CATEGORY_LOADING: "CATEGORY_LOADING",
  PRODUCTS_LISTS_LOADING: "PRODUCTS_LISTS_LOADING",
  REVIEW_LOADING: "REVIEW_LOADING",
};
