export const USER_AUTH_TYPES = {
  LOGIN: {
    LOAD_LOGIN: "LOAD_LOGIN",
    LOAD_LOGGGED_USER: "LOAD_LOGGED_USER",
  },
  SIGNUP: {
    LOAD_SIGNUP: "LOAD_SIGNUP",
    LOAD_SIGNED_UP_USER: "LOAD_SIGNED_UP_USER",
  },
  MESSAGE: {
    LOAD_AUTH_SUCCESS_MESSAGE: "LOAD_AUTH_SUCCESS_MESSAGE",
    LOAD_AUTH_FAILURE_MESSAGE: "LOAD_AUTH_FAILURE_MESSAGE",
  },
  USER_STATUS: {
    LOAD_ACCREDITATION: "LOAD_ACCREDITATION",
    IS_LOGGED_IN: "IS_LOGGED_IN",
  },
};

export const COOKIE_NAMES = {
  AUTH_TOKEN: "AUTH_TOKEN",
};
